version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: techhub-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: strongpassword123
    volumes:
      - mongodb_data:/data/db
    networks:
      - techhub-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: techhub-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
      - MONGO_URL=mongodb://admin:strongpassword123@mongodb:27017/techhub?authSource=admin
    depends_on:
      - mongodb
    networks:
      - techhub-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://5.129.251.89
    container_name: techhub-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - techhub-network

volumes:
  mongodb_data:

networks:
  techhub-network:
    driver: bridge
