version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: techhub-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      HOST: 0.0.0.0
      MONGO_URL: "mongodb+srv://first_db:14022002Natya@cluster0.ep52u7w.mongodb.net/TECH_HUB?retryWrites=true&w=majority"
      JWT_SECRET: My_Secret_Super_Strong_Key_2024_TechHub_12345
    networks:
      - techhub-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://vitalii-shiluk-10-12-25.result-student.tw1.ru:5000
    container_name: techhub-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - techhub-network

networks:
  techhub-network:
    driver: bridge
